-- Generated by scripts/generate-seed.ts. Do not edit by hand.
--
-- Mirrors the current contents of src/data into Supabase so the panel starts
-- from exactly what the site already publishes. Re-run `npm run seed` after
-- changing src/data, then apply the file.

-- Announcements ------------------------------------------------------------
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('g1-2027-applications', 'Grade 1 admissions for 2027 now open', 'Applications for admission to Grade 1 in the 2027 academic year are now open under Ministry Circular No. 25/2026. Children must complete five years of age by 31 January 2027. Applications must be submitted by registered post to at least six schools, including at least three Provincial Council schools near your residence, in order of preference, and must be received on or before 30 July 2026.', 'Admissions', 'urgent', '2026-06-30', '2026-07-30', true, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('intermediate-vacancies', 'Vacancies arising at intermediate grades', 'Applications are invited for existing vacancies at intermediate grades under Ministry Circular No. 09/2026. Vacancies are calculated as at 31 January 2026, with class capacities of 40 for Grades 2 to 5 and 45 for Grades 6 to 11. All admissions must be completed before 27 April 2026.', 'Admissions', 'important', '2026-03-31', null, false, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('g1-provisional-list', 'Grade 1 provisional admission list published', 'The provisional admission list for Grade 1 is published on school noticeboards and on the college website. Formal appeals or objections must be lodged by 31 October 2026.', 'Admissions', 'important', '2026-10-15', '2026-10-31', false, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('anti-corruption-admission', 'No payment or donation in connection with admission', 'Ministry circulars strictly prohibit donations or payment of any kind in connection with admission to national schools. Any request for such payment should be reported to the school.', 'Circulars', 'info', '2026-06-25', null, true, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('medium-of-instruction', 'Medium of instruction at entry stage', 'Admissions at entry stage are limited to Sinhala and Tamil mediums. There are no direct admissions to the English medium. For schools operating bi-medium curricula, applications may be made under one medium only, and the medium cannot be changed after selection.', 'Admissions', 'info', '2026-06-25', null, false, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('unit-test-papers', 'Unit test papers available for download', 'Unit test papers are published for download. Candidates should confirm the current paper series with their subject teacher before sitting a test.', 'Examinations', 'info', '2026-09-01', null, false, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('audited-accounts', 'Audited financial statement published', 'The audited financial statement for the Society for the period 1 January to 31 December 2025 has been published and is available for inspection.', 'General', 'info', '2026-06-13', null, false, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;
insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)
values ('cadet-band-championship', 'National Cadet Band Championship reclaimed', 'The Western Cadet Band has secured the All Island Cadet Band Championship, reclaiming the title after 25 years.', 'General', 'info', '2026-10-01', null, false, '[]'::jsonb, true)
on conflict (id) do update set
  title = excluded.title, body = excluded.body, category = excluded.category,
  severity = excluded.severity, published_at = excluded.published_at,
  expires_at = excluded.expires_at, pinned = excluded.pinned,
  attachments = excluded.attachments, published = excluded.published
where public.announcements.updated_at = public.announcements.created_at;

-- Media slots --------------------------------------------------------------
insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('hero-campus', 'hero', '/nalanda-web/images/gallery/malalasekara-theatre.jpeg', null, 'Interior of the Malalasekara auditorium, where the college assembles', 2048, 1152, 'Plate I · Photograph: Kavindu Mahanaam, CC BY-SA 4.0, via Wikimedia Commons.', false, 'I', 'Kavindu Mahanaam', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'https://commons.wikimedia.org/wiki/File:Malalasekara_Theatre.jpeg', false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('archival-1925', 'gallery', 'https://picsum.photos/seed/nalanda-1925-original-classrooms/1200/900', null, 'Placeholder: the block of sixteen rooms raised in 1924, twelve of them classrooms', 1200, 900, 'Awaiting photograph — the original sixteen rooms raised in 1924.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('malalasekara-hall', 'gallery', '/nalanda-web/images/gallery/malalasekara-theatre.jpeg', null, 'Interior of the Malalasekara auditorium, photographed as it was completed', 2048, 1152, 'Photograph: Kavindu Mahanaam, CC BY-SA 4.0, via Wikimedia Commons.', false, null, 'Kavindu Mahanaam', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'https://commons.wikimedia.org/wiki/File:Malalasekara_Theatre.jpeg', false, 1, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('play-ground', 'gallery', '/nalanda-web/images/gallery/play-ground.jpeg', null, 'The college play ground', 960, 720, 'Photograph: Kavindu Mahanaam, CC BY-SA 4.0, via Wikimedia Commons.', false, null, 'Kavindu Mahanaam', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'https://commons.wikimedia.org/wiki/File:Nalada_College_Play_Ground.jpeg', true, 2, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('nalanda-tv', 'gallery', '/nalanda-web/images/gallery/nalanda-tv.jpg', null, 'The studio from which Nalanda TV was broadcast by the college Communication Unit in 2019', 2048, 1365, 'Photograph: Sherloque Wells, CC BY-SA 4.0, via Wikimedia Commons.', false, null, 'Sherloque Wells', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'https://commons.wikimedia.org/wiki/File:Nalanda_TV.jpg', true, 3, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('science-day', 'gallery', '/nalanda-web/images/gallery/science-day.jpg', null, 'An announcement at a Nalanda College Science Day in the 1980s', 690, 478, 'Photograph: Sherloque Wells, CC BY-SA 4.0, via Wikimedia Commons.', false, null, 'Sherloque Wells', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'https://commons.wikimedia.org/wiki/File:Nalanda_Science_Day_Announcing.jpg', false, 4, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('astronomy-night', 'gallery', '/nalanda-web/images/gallery/eclipse-nalanda.jpg', null, 'The total solar eclipse of 26 January 2009, observed from the college grounds by the Astronomical Society', 1500, 1125, 'Photograph: Bruno Sanchez-Andrade Nuño, CC BY 2.0, via Wikimedia Commons.', false, null, 'Bruno Sanchez-Andrade Nuño', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 'https://commons.wikimedia.org/wiki/File:Sri_Lanka%27s_Best_Pictures_From_Eclipse_%40_Nalanda_Grounds_by_NCAS_%283242898237%29.jpg', true, 5, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('centenary-project', 'gallery', 'https://picsum.photos/seed/nalanda-centenary-innovation-centre/1200/900', null, 'Placeholder: rendering of the Innovation Center', 1200, 900, 'Awaiting published design or photograph — the Centenary Innovation Center.', true, null, null, null, null, null, false, 6, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('sports-arena', 'gallery', 'https://picsum.photos/seed/nalanda-centenary-sports-arena/1200/900', null, 'Placeholder: rendering of the Sports Arena', 1200, 900, 'Awaiting published design or photograph — the Centenary Sports Arena.', true, null, null, null, null, null, false, 7, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('swimming-pool', 'gallery', 'https://picsum.photos/seed/nalanda-swimming-pool/1200/900', null, 'Placeholder: the college swimming pool', 1200, 900, 'Plate IV · Awaiting photograph — the swimming pool.', true, 'IV', null, null, null, null, false, 8, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('cadet-band', 'gallery', 'https://picsum.photos/seed/nalanda-western-cadet-band/1200/900', null, 'Placeholder: the Western Cadet Band in formation', 1200, 900, 'Plate V · Awaiting photograph — the Western Cadet Band.', true, 'V', null, null, null, null, false, 9, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('big-match', 'gallery', 'https://picsum.photos/seed/battle-of-the-maroons-cricket/1200/900', null, 'Placeholder: the Battle of the Maroons', 1200, 900, 'Plate VI · Awaiting photograph — the Battle of the Maroons or a major school fixture.', true, 'VI', null, null, null, null, false, 10, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('hostel-library', 'gallery', 'https://picsum.photos/seed/nalanda-hostel-library/1200/900', null, 'Placeholder: the hostel library opened in September 2026', 1200, 900, 'Plate III · Awaiting photograph — the hostel library.', true, 'III', null, null, null, null, false, 11, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('campus-pavilion', 'campus', 'https://picsum.photos/seed/nalanda-college-pavilion/1400/1000', null, 'Placeholder: the college pavilion', 1400, 1000, 'Awaiting photograph — the college pavilion.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('campus-languages', 'campus', 'https://picsum.photos/seed/nalanda-language-laboratory/1400/1000', null, 'Placeholder: the language laboratory', 1400, 1000, 'Awaiting photograph — the language laboratory.', true, null, null, null, null, null, false, 1, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('campus-computer-lab', 'campus', 'https://picsum.photos/seed/nalanda-computer-laboratory/1400/1000', null, 'Placeholder: the computer laboratories', 1400, 1000, 'Plate II · Awaiting photograph — a science or computer laboratory.', true, 'II', null, null, null, null, false, 2, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('campus-hostel', 'campus', 'https://picsum.photos/seed/nalanda-college-hostel/1400/1000', null, 'Placeholder: the college hostel', 1400, 1000, 'Awaiting photograph — the college hostel.', true, null, null, null, null, null, false, 3, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('national-cadet-band-championship', 'news', 'https://picsum.photos/seed/nalanda-western-cadet-band-championship/1200/800', null, 'Seeded placeholder for the news story national cadet band championship', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('first-carbon-footprint-neutral-school', 'news', 'https://picsum.photos/seed/nalanda-carbon-neutral-campus/1200/800', null, 'Seeded placeholder for the news story first carbon footprint neutral school', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('hostel-library-opening', 'news', 'https://picsum.photos/seed/nalanda-hostel-library-opening/1200/800', null, 'Seeded placeholder for the news story hostel library opening', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('centennial-swimming-fiesta', 'news', 'https://picsum.photos/seed/nalanda-swimming-fiesta/1200/800', null, 'Seeded placeholder for the news story centennial swimming fiesta', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('ranaviru-upahara-2026', 'news', 'https://picsum.photos/seed/ranaviru-upahara/1200/800', null, 'Seeded placeholder for the news story ranaviru upahara 2026', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('sports-icon-of-the-century', 'news', 'https://picsum.photos/seed/nalanda-sports-icon/1200/800', null, 'Seeded placeholder for the news story sports icon of the century', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;

insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)
values ('societies-audited-accounts', 'news', 'https://picsum.photos/seed/nalanda-audited-accounts/1200/800', null, 'Seeded placeholder for the news story societies audited accounts', 1200, 800, 'Awaiting photograph from the college archive.', true, null, null, null, null, null, false, 0, true)
on conflict (id) do update set
  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,
  width = excluded.width, height = excluded.height, credit = excluded.credit,
  placeholder = excluded.placeholder, plate = excluded.plate,
  source_author = excluded.source_author, source_license = excluded.source_license,
  source_license_url = excluded.source_license_url, source_page = excluded.source_page,
  on_home = excluded.on_home, sort_order = excluded.sort_order
where public.media_slots.updated_at = public.media_slots.created_at;


-- News articles ------------------------------------------------------------
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('national-cadet-band-championship', 'Nalanda College Reclaims National Cadet Band Championship After 25 Years', 'The Western Cadet Band of Nalanda College has secured the championship at the All Island competition.', ARRAY['The Western Cadet Band of Nalanda College has achieved a remarkable milestone, securing the Championship at the All Island Cadet Band Championship.', 'The title returns to the college after an absence of 25 years, and reflects the sustained work of the band''s instructors and the cadets who have drilled through the year.', 'Cadet banding remains one of the college''s most demanding extra-curricular commitments, requiring regular early-morning practice and a high standard of musical discipline.']::text[], 'Achievements', '2026-10-01', 2, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('first-carbon-footprint-neutral-school', 'Sri Lanka''s First Carbon Footprint Neutral School', 'The college is officially recognised as Sri Lanka''s first carbon footprint neutral school.', ARRAY['Nalanda College has been officially recognised as Sri Lanka''s first carbon footprint neutral school, creating another unique record for the institution.', 'The recognition follows sustained work on the environmental footprint of a campus of more than four thousand students, and places the college among the first schools in the country to reach this standard.', 'It is a marker of how the second century of the school is being framed: continuity of Buddhist scholarly tradition alongside a contemporary responsibility to the country it serves.']::text[], 'Achievements', '2026-06-05', 2, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('hostel-library-opening', 'Hostel Library Opening Ceremony', 'The Hostel Library was officially opened, introducing a new space dedicated to learning, reading and academic enrichment.', ARRAY['The Hostel Library was officially opened, introducing a new space dedicated to learning, reading and academic enrichment.', 'The facility gives boarders a dedicated place to study within the hostel, reducing the need to travel to other facilities during study periods.', 'The newly established space is part of continued investment in boarding life at the college.']::text[], 'School News', '2026-09-17', 1, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('centennial-swimming-fiesta', 'Nalanda Centennial Swimming Fiesta', 'A celebration of speed, grit and sporting excellence, held on 10 September at the Centennial Swimming Fiesta.', ARRAY['The spirit of sporting excellence took centre stage at the Nalanda Centennial Swimming Fiesta, held on 10 September.', 'The meet formed part of the centenary programme of sporting events, extending a tradition that includes athletics, boxing, aquatics and rugby.', 'The Old Nalandians'' Sports Club, established in 1967, continues to organise major fixtures including the Centennial Rugby Fiesta and the Centennial Boxing Fiesta.']::text[], 'School News', '2026-09-11', 2, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('ranaviru-upahara-2026', 'Ranaviru Upahara 2026', 'The Nalanda Junior Old Boys'' Association presents Ranaviru Upahara 2026, honouring war heroes.', ARRAY['The Nalanda Junior Old Boys'' Association proudly presents Ranaviru Upahara 2026, a special gathering organised to honour the courage, dedication and sacrifice of the fallen.', 'The commemoration is held in tribute to Nalandian war heroes who made the supreme sacrifice in defence of the country.', 'Ranaviru Upahara 2026 was held as a dedicated remembrance, with a further tribute event for the war heroes.']::text[], 'School News', '2026-08-06', 1, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('sports-icon-of-the-century', 'Old Nalandians Sports Club - Nalanda Sports Icon of the Century', 'The Old Nalandians Sports Club is recognised as Nalanda Sports Icon of the Century.', ARRAY['The legendary history of Nalanda College has been written in part by its Old Nalandians, and the Sports Icon of the Century award recognises the club''s contribution to that history.', 'Founded in 1967, the Old Nalandians'' Sports Club continues to organise school fixtures and alumni sporting events across rugby, boxing and other codes.']::text[], 'Achievements', '2026-06-29', 1, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;
insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)
values ('societies-audited-accounts', 'Audited Financial Statement for the Society', 'The audited financial statement for the period 1 January to 31 December 2025 has been published.', ARRAY['The audited financial statement of the Society for the period 1 January to 31 December 2025 has been completed and published.', 'The statement is available for inspection by interested parties.']::text[], 'School News', '2026-06-13', 1, null, true)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,
  category = excluded.category, published_at = excluded.published_at,
  read_minutes = excluded.read_minutes, published = excluded.published
where public.articles.updated_at = public.articles.created_at;

-- 8 announcements, 7 articles, 24 media slots.
