/**
 * Regenerates supabase/seed.sql from the TypeScript content modules.
 *
 * The seed is generated rather than hand-written for one reason: it has to
 * agree with src/data. A transcription slip would seed a title that differs from
 * the one the components already render, and the site would quietly change the
 * moment CONTENT_SOURCE flipped to supabase. Reading the same objects the site
 * renders makes that impossible.
 *
 * Run after editing anything in src/data:
 *
 *   npm run seed
 *
 * The output is applied by `supabase db reset`, or pasted into the SQL editor
 * for an existing project. It is idempotent, and re-running it is safe against a
 * database that real editors are using.
 *
 * Every statement upserts on the natural key, but behind a `where` guard: a row is
 * only refreshed if `updated_at = created_at`, which means nothing has updated it
 * since it was inserted. Once the panel has touched a row, the `updated_at` trigger
 * has moved its timestamp and the seed leaves it alone. Without that guard, pasting
 * this file into a live project would silently revert published work — which is the
 * kind of mistake nobody notices until a parent reads a withdrawn admission notice.
 *
 * The consequence worth knowing: if you edit a seeded row's content in `src/data`
 * and re-run this against a project where that row has already been edited in the
 * panel, your change is skipped. Refresh such a row with `supabase db reset`
 * locally, or update it in the panel, where the change is made deliberately.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

import { ANNOUNCEMENTS } from "@/data/announcements";
import { ARTICLES } from "@/data/news";
import {
  CAMPUS_SLOTS,
  GALLERY_SLOTS,
  HERO_MEDIA,
  HOME_PHOTOS,
  type MediaSlot,
} from "@/data/media";
import { ASSET_BASE } from "@/constants/site";

const OUT = path.resolve(process.cwd(), "supabase/seed.sql");

/** Single-quoted SQL literal. Doubling the quote is the only escape Postgres needs. */
const text = (value: string | null | undefined): string => {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
};

const int = (value: number): string => String(Math.trunc(value));

const bool = (value: boolean): string => (value ? "true" : "false");

const jsonb = (value: unknown): string =>
  `'${JSON.stringify(value ?? null).replace(/'/g, "''")}'::jsonb`;

/** Postgres array literal, element order preserved. */
const array = (values: readonly string[]): string =>
  `ARRAY[${values.map(text).join(", ")}]::text[]`;

const lines: string[] = [];

const header = `-- Generated by scripts/generate-seed.ts. Do not edit by hand.
--
-- Mirrors the current contents of src/data into Supabase so the panel starts
-- from exactly what the site already publishes. Re-run \`npm run seed\` after
-- changing src/data, then apply the file.
`;

lines.push(header);

// ---------------------------------------------------------------------------
// Announcements
// ---------------------------------------------------------------------------

lines.push(`-- Announcements ------------------------------------------------------------`);
for (const a of ANNOUNCEMENTS) {
  const row: Record<string, string> = {
    id: text(a.id),
    title: text(a.title),
    body: text(a.body),
    category: text(a.category),
    severity: text(a.severity),
    published_at: text(a.publishedAt),
    expires_at: text(a.expiresAt ?? null),
    pinned: bool(Boolean(a.pinned)),
    attachments: jsonb(a.attachments ?? []),
    published: bool(true),
  };
  lines.push(
    `insert into public.announcements (id, title, body, category, severity, published_at, expires_at, pinned, attachments, published)\n` +
      `values (${Object.values(row).join(", ")})\n` +
      `on conflict (id) do update set\n` +
      `  title = excluded.title, body = excluded.body, category = excluded.category,\n` +
      `  severity = excluded.severity, published_at = excluded.published_at,\n` +
      `  expires_at = excluded.expires_at, pinned = excluded.pinned,\n` +
      `  attachments = excluded.attachments, published = excluded.published\n` +
      // See NEVER_EDITED. This is what stops a re-run from reverting live content.
      `where public.announcements.updated_at = public.announcements.created_at;`,
  );
}
lines.push("");

// ---------------------------------------------------------------------------
// Media slots
// ---------------------------------------------------------------------------

const homeIds = new Set(HOME_PHOTOS.map((slot) => slot.id));

/**
 * One row per slot, wherever it appears.
 *
 * A photograph that is both the hero and a gallery frame stays two rows, because
 * they are two editorial decisions: the hero can be replaced without touching
 * the gallery, and the gallery frame carries different alt text. The credits
 * page already collapses them back into one entry per source page.
 */
function slotRow(
  slot: MediaSlot,
  gallery: "hero" | "gallery" | "campus" | "news",
  sortOrder: number,
  onHome: boolean,
): string {
  const row: Record<string, string> = {
    id: text(slot.id),
    gallery: text(gallery),
    src: text(slot.src),
    storage_path: text(null),
    alt: text(slot.alt),
    width: int(slot.width),
    height: int(slot.height),
    credit: text(slot.credit),
    placeholder: bool(slot.placeholder),
    plate: text(slot.plate ?? null),
    source_author: text(slot.source?.author ?? null),
    source_license: text(slot.source?.license ?? null),
    source_license_url: text(slot.source?.licenseUrl ?? null),
    source_page: text(slot.source?.page ?? null),
    on_home: bool(onHome),
    sort_order: int(sortOrder),
    published: bool(true),
  };

  return (
    `insert into public.media_slots (id, gallery, src, storage_path, alt, width, height, credit, placeholder, plate, source_author, source_license, source_license_url, source_page, on_home, sort_order, published)\n` +
    `values (${Object.values(row).join(", ")})\n` +
    `on conflict (id) do update set\n` +
    `  gallery = excluded.gallery, src = excluded.src, alt = excluded.alt,\n` +
    `  width = excluded.width, height = excluded.height, credit = excluded.credit,\n` +
    `  placeholder = excluded.placeholder, plate = excluded.plate,\n` +
    `  source_author = excluded.source_author, source_license = excluded.source_license,\n` +
    `  source_license_url = excluded.source_license_url, source_page = excluded.source_page,\n` +
    `  on_home = excluded.on_home, sort_order = excluded.sort_order\n` +
    // Deliberately excludes `storage_path` and `published`: a photograph an
    // editor uploaded lives at a storage path src/data has never heard of, and
    // overwriting it with null would orphan the file.
    `where public.media_slots.updated_at = public.media_slots.created_at;\n`
  );
}

lines.push(`-- Media slots --------------------------------------------------------------`);
lines.push(slotRow(HERO_MEDIA, "hero", 0, false));
GALLERY_SLOTS.forEach((slot, index) => {
  lines.push(slotRow(slot, "gallery", index, homeIds.has(slot.id)));
});
CAMPUS_SLOTS.forEach((slot, index) => {
  lines.push(slotRow(slot, "campus", index, false));
});

// News thumbnails are seeded as explicit slots so an editor can replace one from
// the panel. `src` points at the same empty-frame asset the site draws for any
// slot still waiting on a photograph, so nothing changes visually until
// somebody uploads a real frame.
const AWAITING_SRC = `${ASSET_BASE}/images/awaiting.svg`;

const newsSlot = (slug: string): MediaSlot => ({
  id: slug,
  src: AWAITING_SRC,
  alt: `Seeded placeholder for the news story ${slug.replace(/-/g, " ")}`,
  width: 1200,
  height: 800,
  credit: "Awaiting photograph from the college archive.",
  placeholder: true,
});
for (const article of ARTICLES) {
  lines.push(slotRow(newsSlot(article.slug), "news", 0, false));
}
lines.push("");

// ---------------------------------------------------------------------------
// Articles
// ---------------------------------------------------------------------------

lines.push(`-- News articles ------------------------------------------------------------`);
for (const a of ARTICLES) {
  const row: Record<string, string> = {
    slug: text(a.slug),
    title: text(a.title),
    excerpt: text(a.excerpt),
    body: array(a.body),
    category: text(a.category),
    published_at: text(a.publishedAt),
    read_minutes: int(a.readMinutes),
    // Left null so the seeded news slot is resolved by slug at build time. Set
    // this only when a story should use a photograph from another collection.
    hero_slot_id: text(null),
    published: bool(true),
  };
  lines.push(
    `insert into public.articles (slug, title, excerpt, body, category, published_at, read_minutes, hero_slot_id, published)\n` +
      `values (${Object.values(row).join(", ")})\n` +
      `on conflict (slug) do update set\n` +
      `  title = excluded.title, excerpt = excluded.excerpt, body = excluded.body,\n` +
      `  category = excluded.category, published_at = excluded.published_at,\n` +
      `  read_minutes = excluded.read_minutes, published = excluded.published\n` +
      `where public.articles.updated_at = public.articles.created_at;`,
  );
}
lines.push("");

const counts = [
  `${ANNOUNCEMENTS.length} announcements`,
  `${ARTICLES.length} articles`,
  `${1 + GALLERY_SLOTS.length + CAMPUS_SLOTS.length + ARTICLES.length} media slots`,
];
lines.push(`-- ${counts.join(", ")}.`);

writeFileSync(OUT, `${lines.join("\n")}\n`, "utf8");

console.log(`Wrote ${path.relative(process.cwd(), OUT)}`);
console.log(`  ${counts.join("\n  ")}`);